ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential ca-certificates git pkg-config python3 dpkg-dev debhelper fakeroot time \
    zlib1g-dev libbz2-dev liblzma-dev libdeflate-dev libcurl4-gnutls-dev \
    libssl-dev libhts-dev samtools tabix \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /build
